services:
  postgres:
    image: postgres:latest
    container_name: pg-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Publicly accessible on port 5432
    networks:
      - my_network  # This keeps communication internal to the Docker network (can be omitted if no internal communication needed)
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./tests/init.sql:/docker-entrypoint-initdb.d/init.sql

  datapilot:
    build: .
    container_name: datapilot-app
    ports:
      - "8501:8501"  # Publicly accessible on port 8501
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
    networks:
      - my_network  # Optional, remove if no communication needed with other services
    depends_on:
      - postgres
  
  python-script:
    image: python:3.9
    container_name: python-runner
    depends_on:
      - postgres
    networks:
      - my_network
    volumes:
      - ./tests/data_import.py:/data_import  # Mount your Python script directory
    working_dir: /scripts
    entrypoint: ["sh", "-c", "while ! nc -z postgres 5432; do sleep 1; done; pip3 install psycopg2-binary; python3 data_import.py"]

  huggingface-tgi:
    image: ghcr.io/huggingface/text-generation-inference:latest
    container_name: text-generation-inference
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      HF_TOKEN: "${HF_TOKEN}"  # Pass the HF_TOKEN environment variable
    volumes:
      - "~/.cache/huggingface:/root/.cache/huggingface"  # Cache directory for Hugging Face
    ports:
      - "8000:80"  # Expose port 8000 on the host to port 80 in the container
    command: --model-id defog/llama-3-sqlcoder-8b


  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   networks:
  #     - my_network  # Optional, remove if no communication needed with other services
  #   volumes:
  #     - ollama:/root/.ollama
  #   ports:
  #     - "9001:9001"  # Publicly accessible on port 11434
  #   environment:
  #     OLLAMA_HOST: http://ollama:9001
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 2G

volumes:
  pg_data:
  ollama:

# Define the network, but you can remove this section if you want to use the default Docker bridge network
networks:
  my_network:
    external: false
